### ISSUE TITLE
Package.Version keyword not parsed.

### ISSUE THREAD

**Issue by xixiaofinland** [aheber/tree-sitter-sfapex#38] opened 2024-10-01 18:54 UTC
FYI. It works in prettier not here. I never used this either.

```
class PackageVersion {
  void packageVersionTest() {
    Object v = Package.Version.1.0;
    v = Package.Version.Request;
  }
}
```

**Comment by aheber** [comment] 2024-10-01 20:10
Very interesting. Thanks for bringing this up. I have an open issue (#25) on the repo to test this type of syntax (in particular with the `System.RunAs` syntax but I haven't gotten around to working on it yet, making sure that works would including being able to support syntax like this. I'm going to close this as a duplicate of that issue but this gives me a more concise test case in addition to what I had listed there.

I'm guessing it is a limitation of the `identifier` not being able to start with a number.

I don't think this is really hard to get working, the tricky bit will be isolating the behavior because fixing this the simple way would likely loosen up other parsing behaviors in ways that would generally be incorrect and make it harder to parse other things. I may have to look at the Jorje output to see how it thinks about isolation on this, maybe it is a super special parsing branch just for this syntax.

**Closed by aheber** 2024-10-01 20:10 UTC
